version: '3.8'
services:
  db1:
    image: postgres:14.6
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - '5432:5432'
    volumes: 
      - db1_vol:/var/lib/postgresql/data
  db2:
    image: postgres:14.6
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - '5433:5432'
    volumes: 
      - db2_vol:/var/lib/postgresql/data
  db3:
    image: postgres:14.6
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - '5434:5432'
    volumes: 
      - db3_vol:/var/lib/postgresql/data
networks:
  default:
    name: dbnet
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.0.0/16
         gateway: 10.10.0.1
volumes:
  db1_vol:
    driver: local
  db2_vol:
    driver: local
  db3_vol:
    driver: local