
create table phenomenon_type (
    id bigint generated by default as identity, 
    name text not null, 
    primary key(id)
);

create table unit (
    id bigint generated by default as identity, 
    name text not null, 
    abbreviation text not null, 
    primary key(id)
);

create table organization (
    id bigint generated by default as identity, 
    name text not null, 
    country text not null, 
    primary key(id)
);

create table users (
    id bigint generated by default as identity, 
    organization bigint references organization(id) not null, 
    name text not null, 
    email text, 
    password text not null, 
    primary key (id)
);

create table station (
    id bigint generated by default as identity, 
    name text not null, 
    number bigint not null, 
    organization bigint references organization(id) not null, 
    type text not null, 
    latitude double precision not null, 
    longitude double precision not null, 
    altitude double precision not null, 
    city text not null, 
    primary key (id)
);

create table device (
    id bigint generated by default as identity, 
    station bigint references station(id) not null, 
    name text not null, 
    primary key (id)
);

create table measurement (
    id bigint generated by default as identity, 
    device bigint references device(id) not null, 
    value double precision not null, 
    time timestamp without time zone not null, 
    type bigint references phenomenon_type(id) not null, 
    unit bigint references unit(id) not null, 
    primary key (id)
);

create index meas_time_idx on measurement (time);

create materialized view station_info as 
    select station.id as id, 
        station.name as station, 
        type as station_type, 
        organization.name as organization, 
        latitude, 
        longitude, 
        altitude, 
        city, 
        organization.country as country 
    from station 
    join organization on station.organization = organization.id;

create materialized view meas_min_max_day as
    select distinct on (station_info, min, max, avg, time, phenomenon_type, unit)
        meas_day.id as id, 
        station_info.id as station_info, 
        meas_day.min as min, 
        meas_day.max as max, 
        meas_day.avg as avg, 
        meas_day.time as time, 
        phenomenon_type.name as phenomenon_type, 
        unit.abbreviation as unit 
    from (
        select id,
            date_trunc('day', time) as time,
            min(value) over (partition by type, unit, date_trunc('day', time)) as min,
            max(value) over (partition by type, unit, date_trunc('day', time)) as max,
            avg(value) over (partition by type, unit, date_trunc('day', time)) as avg,
            device,
            type,
            unit
        from measurement
    ) meas_day
    join device on meas_day.device = device.id
    join station_info on device.station = station_info.id
    join phenomenon_type on meas_day.type = phenomenon_type.id
    join unit on meas_day.unit = unit.id;

create index meas_view_time_idx on meas_min_max_day (time);
